---
# db_checks.yml
# Undertake basic db validation

- name: "db_checks 1. create directory {{ script_dir }}"
  action: file dest={{ script_dir }} state=directory owner=oracle group=oinstall
  tags:
    - precheck

- name: db_checks 2. scripts - copy
  copy: src=files/{{ item }} dest={{ script_dir }} owner=oracle group=oinstall mode=0700
  with_items:
   - db_details.sh
   - db_details.sql
   - restart_db.sh
   - shutdown_db.sql
   - startup_db.sql
   - test.sh
  tags:
    - precheck
    - test
    - upload

- name: "db_checks 3. instance found check {{ sid_pattern }}"
  action: shell ps -aef | grep pmon | awk -F_ '{print $3}' | grep -v "^$"  | sort -n | sed s/" "//g | grep -i "{{ sid_pattern }}"
  register: oracle_sid
#  failed_when:  oracle_sid.stdout|trim  == '' or "{{ sid_pattern }}" not in oracle_sid.stdout
  failed_when:  oracle_sid.stdout|trim  == ''
  changed_when: False
  tags:
    - precheck
    - test

- name: db_checks 4. display oracle_sid
  debug:
    msg:
      - " oracle_sid: {{ oracle_sid.stdout }}"
  tags:
    - test
    - precheck
...
